# Generated by Django 3.0.4 on 2020-03-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hex_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
