# Generated by Django 3.0.4 on 2020-03-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0003_auto_20200326_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.IntegerField(default=170),
        ),
    ]
